<link rel="stylesheet" href="<?php echo $this->baseUrl("css/jquery.dataTables.css"); ?>" type="text/css" media="all">
<h4 style="width:100%;height:50px;border-bottom:1px solid #777;">
    <div style="font-size:22.5px;line-height:36px;color:#333;float:left;">
        Participant Required Attention
    </div>
</h4>
<input type="hidden" id="scheme" name="scheme" value="<?php echo $this->schemes[0]['scheme_id']; ?>"  >
<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered table-hover"
       id="reportTable">
    <thead>
        <tr>
            <th>PT ID</th>
            <th>Lab Name</th>
            <th>Country Name</th>
            <th>Score</th>
            <th>Number Of Error In Last Month</th>
            <th>Total Number Of Tests Performed In Last Month</th>
            <th>Error Rate</th>
            <th>Reflaxive Comment</th>
            <th>Instrument Used</th>
            <th>Cartridge expiration date</th>
            <th>Submission Comment</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td colspan="10" class="dataTables_empty">Loading data from server</td>
        </tr>
    </tbody>
</table>

<script>
$(document).ready(function(){
    drawTable();
});
function drawTable() {
        oTable = $('#reportTable').dataTable({
            "oLanguage": {
                "sLengthMenu": "_MENU_ records per page",
                "sEmptyTable": "No shipment schemes under this Distribution yet"
            },
            "bJQueryUI": false,
            "bAutoWidth": false,
            "bInfo": true,
            "bScrollCollapse": true,
            "sPaginationType": "bootstrap",
            "bRetrieve": false,
            "bDestroy": true,
            "aoColumns": [
                {"sClass": "center"},
                {"sClass": "center"},
                {"sClass": "center"},
                {"sClass": "center"},
                {"sClass": "center"},
                {"sClass": "center"},
                {"sClass": "center"},
                {"sClass": "center"},
                {"sClass": "center"},
                {"sClass": "center"},
                {"sClass": "center", "bSortable": false}
            ],
            "aaSorting": [[3, "desc"]],
            "bProcessing": true,
            "bServerSide": true,
            "sAjaxSource": "<?php echo $this->url(array('module' => 'reports', 'controller' => 'xtpt-indicators', 'action' => 'participant-attention', 'format' => 'html')); ?>",
            "fnServerParams": function (aoData) {
                aoData.push({"name": "distribution", "value": '<?php echo $this->selectedDistribution ?>'});
            },
            "fnServerData": function (sSource, aoData, fnCallback) {
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
                });
            }, "fnRowCallback": function (nRow, aData, iDisplayIndex) {
                $('td.sorting_1').addClass('goga');
            },
        });
        <?php
        if (isset($this->searchData) && $this->searchData != '') { ?>
            oTable.fnFilter('<?php echo $this->searchData; ?>');
        <?php
        } ?>
    }

</script>